server:
  port: 8888
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      config:
        server-addr: @nacos-addr@
        # 配置文件 推荐yaml后缀
        file-extension: yaml
  config:
    import:
      # 配置文件 推荐yaml后缀
      - nacos:test_gateway.yaml


