server:
  port: 8000
#  servlet:
#    context-path: /provider
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      config:
        server-addr: @nacos-addr@
        # Nacos页面的配置文件后缀 推荐yaml后缀
        file-extension: yaml
  config:
    import:
      # Nacos页面的配置文件DataId
      - nacos:@artifactId@
