server:
  port: 8888
spring:
  application:
    name: @artifactId@
  config:
    import:
      - nacos:@artifactId@
  cloud:
    nacos:
      config:
        server-addr: @nacos-addr@
        # 配置文件 推荐yaml后缀
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lower-case-service-id: true
      routes:
        - id: test-provider           # 唯一路由表示，没有实际作用不重复就好，建议配合服务名
          uri: lb://test-provider     # 匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错！！！
          predicates:
            - Path=/provider/**         # 以`consumer`开头的请求都负载到`nacos-consumer`服务
          filters:
            - RewritePath=/provider/?(?<segment>.*), /$\{segment}

#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.ipc.netty: DEBUG
#    reactor.netty: DEBUG